### ISSUE TITLE
[frontend] button handler coverage issue

### ISSUE THREAD

**Issue by th-snu** [swsnu/swpp2019-team10#38]
currently AddReview.js is suffering from lack of coverage, and I found that most of uncovered line is from button handlers.

![image](https://user-images.githubusercontent.com/54742258/68218477-ba725100-0027-11ea-9274-9d88498b223a.png)
currently some button is using onClick handler and it seems to be working correctly when I actually run the frontend and test it.

![image](https://user-images.githubusercontent.com/54742258/68218647-06bd9100-0028-11ea-9b63-72856120d3c8.png)
however, even if I simulate clicking the button, jest doesn't count them as covered lines.

could anyone give some help on covering those handler functions?

**Comment by jyeok** [comment]
Since you didn't divide content upload part, image upload part, and backend interaction part (axios)

you should test **all** below at once:
(1) when you click submit button, **it should call addReviewHandler**
(2) it should call **postContentHandler**
(3) it should call **postImageHandler**
(4) in postContentHandler, it should call `axios.post`
(5) by calling axios.post, **store get new State successfully**
(6) same in postImageHandler.

**Comment by th-snu** [comment]
What I said is about coverage, not actual function. and I think unlike component's function, function body calling other function is guaranteed thing without test..

**Comment by th-snu** [comment]
It was just my mistake, in test case condition button is disabled
